theme: jekyll-theme-slate
title: Supporting Women and Minorities in Computer Science
description: Supporting Women and Minorities in Computer Science (or SWMCS for short), is an organization at the University of Hawaii at Manoa aiming to create a better environment for students from under represented groups in the Information and Computer Science Department. 
